### ISSUE TITLE
Merge ~ Bonus ~ entries into same game

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#105]
~ Bonus ~ achievements are achievements that are considered too hard for the base set, or require glitches. They don't count towards mastery of a set or the 400 point limit.

Currently, to earn ~ Bonus ~ achievements, the player has to patch their ROM so it generates a new MD5 and fetches the ~ Bonus ~ achievement set. Instead, ~ Bonus ~ achievements should be considered part of the main game.

Suggested implementation would be to add another flag. Right now, the flags appear to be:
* 1 - active
* 2 - core
* 4 - unofficial

So, adding an 8 - bonus would seem straightforward.

When loading a game, Core and Unofficial achievements are already fetched and separated. The ~ Bonus ~ achievements would also be fetched at the same time, and activated with the Core achievements. This would allow players to earn any missing Core achievements while they're working on the ~ Bonus ~ achievements, and wouldn't require patching their ROM.

However, to make this work, we'd have to have some way to distinguish ~ Bonus ~ achievements from Core achievements on the web page and the overlays in RA_Integration and RetroArch. Additionally, RA_Integration would have to be modified to mark achievements as ~ Bonus ~, and existing ~ Bonus ~ sets would have to be migrated into their base game.

There may be additional work on the server to determine when a user Masters a set.

**Comment by kdecks** [comment]
I recall @GameDragon2k making a prototype of this, in part. (No able to earn both types at the same time)

**Comment by GameDragon2k** [comment]
The prototype still exists, but there is no reason to continue with it now. It was built on the premise that there would not be any server-side extensions to handle bonus sets.

But that isn't the case anymore, so it should be handled in a more proper manner.

**Comment by kdecks** [comment]
please note on RASuite https://github.com/RetroAchievements/RASuite/issues/74

**Comment by Jamiras** [comment]
Adding a note here, but it applies to several of the linked topics as well: Achievements in Bonus sets should not affect the player's Completion rate. Or, if it does, it should be counted as excess of 100%.

For example, if a player only plays one game and completes 100% of the base game, and 10% of the bonus set, their average completion percentage should be either 100% or 110%, not 55%.

**Comment by Thoooreau** [comment]
I'd rather not counting bonus cheevos to the completion rating, so leaving at 100%. Otherwise 200% is going to be the new 100%.

**Comment by GameDragon2k** [comment]
Originally, I thought of not including Bonus sets into any form of completion percentage and simply have the additional points be the rewarding factor for them.

I am unsure if that's still a decent route to take.

**Comment by magusLOGS** [comment]
I think the additional Sets like Bonus, Multiplayer etc. should get their own identity/percentage ratio and Completion Badge as well because without it many player don't want to bother with those Sets and its a good oppurtunity to make some creative and challenging Achievements, unlike the usual Progression Achievements in Core based which are mostly based on Main Game and collecting Items with few additional other Achievements.

I would like to see the additional Sets getting better treatment, which could also bring new users to the Site who think the Achievements in Core are to easy or not challenging/interesting enough because its always the same Achievement types just copy pasted. However, most player do prefer the basic Progression Achievements to get their Master a Core Set Badge in their profile.

High quality Bonus/Multiplayer Sets would be more for the Pro Gamer audience/streamers etc. so additional content shouldn't just be a placeholder for difficult Achievements but a proper treatment for more creative and complex Challenges, the Toolkit is contantly improving so do the Achievements and the possibilities to create some really interesting ones.

Sharing resources without cutting off on oppurtunities, Hard Type Hacks or any Hack in general which is using the same RAM could be binded to the (original source) Game Page, which would be easier for any future Hack to make Achievements for, also easier to find on the Game List, there just needs to be one option that binds the Hack MD5 only to a specific Achievement Group to exclude SMW Core (for example) being unlocked when playing a SWM Hack, same the other way around, SMW Hack should be locked when playing Original SMW so there needs to be some sort of MD5 Firewall builld into the Game Page but in the end it would be worth it by allowing to create multiple variations of same base Game, mostly Hard Type Hacks, Level Hacks. Most Hacks do have the same RAM adresses, only few (higher quality) have changed RAM adresses.

When you build something like this then you have to see the whole picture (think big) otherwise it will be just a alternative Container for Challenges nobody plays because there is nothing to earn, which is missed oppurtunity to make RetroAchievements something really interesting in future because picking up Items really gets boring after a while and there are many players who want to be challenged and getting a reward for doing it.
