### ISSUE TITLE
Retro Point Calculation Issue

### ISSUE THREAD

**Issue by Tsearo** [RetroAchievements/RAWeb#1320]
It looks like the calculation for RR broke at some point because achievements are now having an RR below 1 which shouldn't be possible. You can see examples of this on the Easy Achievements page - https://retroachievements.org/achievementList.php?s=4&p=2
![image](https://user-images.githubusercontent.com/4047771/212740141-b64f295f-360b-4f32-b08e-eb9095a15f24.png)
![image](https://user-images.githubusercontent.com/4047771/212740164-33c19555-e3fe-4203-b067-42d7ae953ded.png)
![image](https://user-images.githubusercontent.com/4047771/212740177-ff51153f-4615-4e31-aaf2-b39ae98f52be.png)

It seems to be affecting achievements with high (90%+) earn rates that include a some softcore earns so the total players calculation may be including only hardcore players but total earns may include softcore causing earns to be higher than total players.

#1286 is the latest change to the calculation so it may have led to this or it's possible the issue has been there longer but gone unnoticed

**Comment by Jamiras** [comment]
It's because of integer truncation.

https://github.com/RetroAchievements/RAWeb/blob/7312c6910915ba6a433f1b1e2efceadd4d94a467/app_legacy/Helpers/database/achievement-points.php#L35-L37

Using the "1 (2)" example:
```
2 * (1.0-0.4) + (2*((312/397)*0.4)
2 *    0.6    + (2 *  0.785  * 0.4)
       1.2    +      0.6287
             1.82

(int)1.82 = 1
```

**Comment by Jamiras** [comment]
Nope, that's not right. `$numHardcoreWinners` is total hardcore players, not winners for the achievement. `$numAchieved` is winners for the achievement. Since total players should always be more than players who earned the achievement, it shouldn't be possible for the result to come out less than the initial value and therefore be truncated.

**Comment by Tsearo** [comment]
Yeah the total players being used in the calculation should be hardcore players only which should have been introduced in #963

**Comment by Jamiras** [comment]
It seems to be a discrepancy caused by Untracked users.

This query returns `$numAchieved=318`:
```
SELECT ach.ID, ach.Points, COUNT(aw.HardcoreMode) AS NumAchieved
      FROM Awarded AS aw 
      LEFT JOIN Achievements AS ach ON aw.AchievementID = ach.ID 
      LEFT JOIN UserAccounts AS ua ON ua.User = aw.User AND NOT ua.Untracked
      WHERE ach.GameID = 10690 AND ach.Flags = 3 AND ach.ID=160436 AND aw.HardcoreMode = 1
      GROUP BY ach.ID
```
But this query returns 312:
```
SELECT ach.ID, ach.Points, COUNT(aw.HardcoreMode) AS NumAchieved
      FROM Awarded AS aw 
      LEFT JOIN Achievements AS ach ON aw.AchievementID = ach.ID 
      LEFT JOIN UserAccounts AS ua ON ua.User = aw.User
      WHERE ach.GameID = 10690 AND ach.Flags = 3 AND ach.ID=160436 AND aw.HardcoreMode = 1
      AND NOT ua.Untracked
      GROUP BY ach.ID
```
And 312/318 is less than 1, and then the integer truncation kicks in.

There are 6 users who have earned that achievement that are untracked. Putting the `AND NOT ua.Untracked` on the JOIN clause appears to include them, but putting it in the WHERE clause appears to exclude them.
