### ISSUE TITLE
Homepage eventually shows red error bar after some time

### ISSUE THREAD

**Issue by Tsearo** [RetroAchievements/RAWeb#1427]
If you leave the homepage up for a while it will eventually show a blank red error line, checking the console it appears to be disconnecting the refresh active players request which is probably a good thing too reduce server load but the error message should probably say something or not show in this case I feel

![image](https://user-images.githubusercontent.com/4047771/224513028-c6de2dcc-9de4-4c5a-9048-767865367085.png)

![image](https://user-images.githubusercontent.com/4047771/224513037-5bf300ff-68a1-40ee-8285-dd7a8f64fda7.png)

![image](https://user-images.githubusercontent.com/4047771/224513048-03490270-682e-481c-a42a-d1263b983931.png)

**Comment by wescopeland** [comment]
The red bar not showing a message turned out to be a separate issue altogether that was resolved during work that happened in https://github.com/RetroAchievements/RAWeb/pull/1439.

It probably does make sense if this component, which is constantly polling the back-end, is silent when a failure happens.
