### ISSUE TITLE
Multiple awards in the set

### ISSUE THREAD

**Issue by JuliaSalsa** [RetroAchievements/RAWeb#143]
I observed players reactions in relation and generally I think Core/Bonus/Multi is a concept which is missing some points. The biggest issue with it right now is the fact Bonus is treated more like a trash bin for all achievements not fitting some standards. I think it would be all better if we should join the core and bonus content together, and use the procentage of achievement. What I want to propose is:

1. Leaving "Hardcore" only as multiplier (no set completion/mastering award in old deifinition no more), or giving points and awards just for "Hardcore", and leaving "Softcore" only with badges, or turning into debug mode with further modifications.
2. Joining the Core and Bonus sets together, as general pool of achievements.
3. Define "goal" flag to mark an achievement (might not be just one, if there are more achievements for completeing the game in a different way)
4. Using total achievements unlocked procentage to define award ranks:
**crown/star on top:** game beaten #56
**0%>25%** one star (bronze - easy*)
**25%>50%** two stars (silver - medium*)
**50%>75%** three stars (gold - hard*)
75%>100% four stars (platinum - master*)
*in well balanced set
5. Rearrange flags to include:
- pending (current unofficial renamed)
- disabled (eventually, to hide unused pending achievements from public, to be displayed only for staff)
- core (current core + bonus content)
- multiplayer (this group of achievements need seperate treatment)
- extension (eventually, to include additional achievements for ROM hacks slightly altering gameplay but with strict rules, which would would limit abusing; I suggest to use current plant for Bonus to create such options)

![badges](https://user-images.githubusercontent.com/35509989/40679355-2fced0c4-6383-11e8-8206-dadf92d29a4a.png)
This pic is just a kind of visualization of the idea, not a complete concept.
In my opinion in such system overall set balance will still be something very important, the bonus content will be included, but will be more justified.

**Comment by kdecks** [comment]
> Joining the Core and Bonus sets together, as general pool of achievements.

Bonus-type achievements needs a different treatment, they need to be isolated. Most bonus achievements are not something that players should be expected to endure.

Bonus **IS** a trash bin; you could look at it like that. It's like NG+++ for people who've mastered everything and still want to toy with the game. These challenges need to be separate from the rest **or we need to completely scrap bonus sets.** 

They usually do break the rules for what is considered good achievements; e.g. too hard, glitch based, or maybe just an overflow when a set gets super bloated.

 ----------------------
I'm all for the tiered awards as presented; great approach.

--------------------------

> extension (eventually, to include additional achievements for ROM hacks slightly altering gameplay but with strict rules, which would would limit abusing; I suggest to use current plant for Bonus to create such options)

Sure, if you want to make mini-sets to feature a hack, why not. This needs to be handled carefully, otherwise it'll get messy.

**Comment by JuliaWolska** [comment]
In my opinion Bonus type of achievements really don't need a seperate treatment, if the set will be "quasi open" (offering not only one award). 
I think what makes a trash bin out of Bonus is high level of arbitrariness, but core list being closed (mandatory to complete to get an award) makes it something eventually exploitable within related intentions.
I've started thinking about including Bonus after having a first dilemma of leaving harder challenge in the set or not, and the vision of it being a "trash bin" came later, and perpetuated with common sense which came afterwards. 
In most cases bonus content is between 30-60% of the size of the regular set, thus even if we would include bonus content, silver or even gold badge will be still within the reach for everyone who can get what we could call core material right now. 
I thought about this concept further, and I think we could leave real procentage hidden, and represented by a procentage of current goal, to make everything look even more "sidetracking". I mean for example:
- if the player will have 8% of total achievemnts will have 32% of bronze goal;
- if they will have 36% it will be 44% of silver goal;
- exact ammount of 50% could just display "you have reached the silver goal";
Additionally we could prearrange that bronze+silver (with completion) will be 100% of the whole set, and gold+platinum will be additional 100% (giving 200% in total).
One thing I forgot to mention, and it's very important - there should be possibility to choose the goal range. Platinum should be availible only for games which currently have a bonus set, or will have such content included. Here is my suggestion:
 - small incomplete set: bronze only
 - any obviously incomplete set: silver max
 - small but complete set (like those meme sets): bronze or silver max
 - complete set, without exceptional challenge: gold max
 - any set with bonus, or exceptional challenge designed: platinum

> Sure, if you want to make mini-sets to feature a hack, why not. This needs to be handled carefully, otherwise it'll get messy.
@GameDragon2k suggested we could use subachievements here, creating single but complex challenges based on unique features.

**Comment by kdecks** [comment]
![image](https://user-images.githubusercontent.com/32706333/41206947-e79c90f2-6cc9-11e8-8b3c-ee701e8e8dc8.png)

**Comment by kdecks** [comment]
An idea I have about dealing with bonus content.
![image](https://user-images.githubusercontent.com/32706333/41206996-d25bc6b2-6cca-11e8-9422-47c3d7e87c8b.png)
Locked means the achievements are default, green means the group of are being processed actively, red means they are off.

**Comment by Thoooreau** [comment]
As I understand, both someone with 80% completion and someone with 100% completion would have platinum badges, is that correct? In this case, wouldn't people think 100% completion should award something better/unique? Also, as badges would be even more the focus of RA, wouldn't people feel incentivized just to reach 75% of a game instead of 100%?

On the other hand, if someone with 100% completion would have a better/unique badge: what if I want to make an insane difficult cheevo, like WR tier or very close? Nowadays I can do it because they fit in bonus sets (specially in the original idea where they didn't even award a badge), but what about in that system? Let's say I wanna do a cheevo in which only 1 person in the world is currently able to achieve it (to incentivize someone like 5 years from now to get to that world record level, like follow your dreams man), would only one or two persons in the world be able to reach the 100% completion and no one else?

**Comment by kdecks** [comment]
I've got more to say on this issue. Will post it later in this box

**Comment by Xeinok-Pals** [comment]
Old thread so I apologize if this is in the wrong place (let me know if I should post elsewhere), but I had some related thoughts/ideas.

**In my experience, there are a few main "types" of achievement hunters:**
1. Casual Hunter - This player is happy to jump into any game, almost disregarding the achievements. They might "beat" the main story of a game and be happy earning a few achievements along the way.
2. Completionists (this or casual hunters might be the largest population) - This type of player strives for 100%s (200%s on RA), they focus on in-game content, in-game acknowledged feats, etc. They are more likely to care about their AGC and might avoid games they seem as impossible to master. Less likely to care about bonus sets.
meleu brought up some good points on complexity/confusion:
3. Challenge Hunter - This player seeks out difficult achievements and can be unhappy if a game is "too easy". They typically dislike glitches/cheese/exploits. They are high-ranked on the site. They are more likely to play bonus sets.
4. Showcase Hunter - This player is somewhat similar to a challenge hunter except that they are going are specific "meaningful" achievements/games that they then like to "show off" not necessarily based on challenge. Currently, RA lacks a way to "showcase" certain favorite achievements, but that feature would make these players very happy.

Making all 4 of these types of achievement hunters happy can be pretty difficult!

**meleu wrote some good points on complexity/confusion:**
> I'm always trying to simplify things. And while thinking on this topic I found an approach where I can see these advantages:
> 
> * simpler to implement (on the server, on the integration and on RetroArch).
> * give freedom to achievement developers to go nuts and create any achievement they can think.
> * minimize revisions.
> * probably minimize the characteristic that bother me the most in this community: rivalry between achievement developers.
> * involve the players community.
> * does not break backward compatibility.

**In addition to the ideas from the posters above, I think one thing that could reduce a lot of subjectivity/confusion is this idea:**
I think it would be a lot more clean of a policy and make much more sense to the majority of people if it's just "challenges baked into the game content" (core set) vs. "challenges not baked into in-game content / totally unacknowledged by the game" (bonus set).

Wario Land is a good example of "kinda difficult but represents in-game content / in-game acknowledgement / in-game reward":
![image](https://user-images.githubusercontent.com/65511279/91596238-a3378380-e919-11ea-9086-8a2e93b108ce.png)

These achievement from SMW though are not represented by in-game content, and have 0 in-game acknowledgement (even though they are not seen as "extremely difficult" by most players, they are not acknowledged in-game):
![image](https://user-images.githubusercontent.com/65511279/91596522-b2b6cc80-e919-11ea-8cf7-3cc559608fc5.png)

The goal should be that more people want to do bonus set-type material - not that core sets get "easier". If the game HAS in-game content for something very difficult, then I think it's just a hard game (Metroid is another example of a game with built-in speedruns in its in-game content). What's pretty much necessary here is with the v2 promise that Core+Bonus can be earned at the same time on the same hash.

**This reduces complexity/confusion/subjectivity because it's no longer about "what is difficult or not" - it simply becomes "is this challenge acknowledged by in-game content or not?".** This means completionist-style players can be rewarded with a "core set mastery" by fully experiencing all the in-game content, with achievements driving them towards interesting easter eggs, full collections/completion/side quests/etc. Challenge Hunter players can focus more on bonus sets and rack up big points for difficult achievements / unique challenges not represented in the game such as deathless runs, strange condition runs, and "what if" kind of challenges. This gives a very simple, clear definition of "core set" and "bonus set".
