### ISSUE TITLE
Forums: Delete Post

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#15]
Forums: 
Add the ability for admin to Delete specific forum posts
For users to delete their own post.

**Comment by meleu** [comment]
IMO forum posts shouldn't be deleted. They should be editable by admins/moderators or the author and closed by admins/moderators. But never deleted.

**Comment by luchaos** [comment]
i'd actually prefer admins/mods not being able to edit other users' content, except for the motto on the user page. users should edit their contents themselves.
we will have soft-deletes, so deleting a user's post can be recovered and remain visible to the author/mods/and admins. allowing it to be edited by others allows for impersonation that may not be visible to non-admins.

**Comment by meleu** [comment]
> i'd actually prefer admins/mods not being able to edit other users' content

how are we going to deal with posts with links to download illegal/copyrighted material on our forums, for example?

**Comment by luchaos** [comment]
the post would be (soft) deleted, so it's only visible to forum mods/the author.
the user should be reminded to not post such links.

for one, that makes the author aware of what is allowed instead of someone else fixing it for them.
it's documented who posted what.

if we still want forum mods to being able to edit other user's posts, there should be a mandatory note that will also be displayed on the post where the mod describes what was changed.

**Comment by meleu** [comment]
Alright. I never saw a forum with this approach but it sounds like a good one! To be honest, at a first glance it seems to be the right thing to do on our community. :wink:
