### ISSUE TITLE
Show who last modified an achievement.

### ISSUE THREAD

**Issue by grenade44** [RetroAchievements/RAWeb#154]
![c6ea71a8-871c-4266-b20b-22d5ab2ec35f](https://user-images.githubusercontent.com/16205775/40839812-eee00cca-659b-11e8-9489-217d866de602.jpeg)

Show who last modified an achievement like it does for who created the achievement.

This way you can see who fixed the achievement as it not always the original dev.

Maybe something easy for @meleu 😉😀

**Comment by meleu** [comment]
Unfortunately this info isn't stored in the database. The current code just spit the "**DeveloperName** made improvements to: **AchievementTitle (Points)**" in the feed and that's all.

The good news is that it's already addressed and we plan to add such feature and much more.

By the way, I'm closing this issue because we have another one (#11) that includes what's being requested here :wink:

**Comment by grenade44** [comment]
Ok cool 👍😎
