### ISSUE TITLE
Unchanged achievement commits should be ignored

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAWeb#206]
It is possible to commit without any change through `RA_Integration` by making a dummy modification and reverting it locally.

Such commits generate misleading comments and feed updates on the website, so they should be ignored.

**Comment by Tsearo** [comment]
I don't believe this is an issue anymore for achievements since you can't publish achievement updates to the site if you revert the achievement back to it's original state as far as I'm aware in the current versions of RA_Integration. 
I did notice however that leaderboards can be pushed still after reverting changes they still appear as modified allowing them to be published without actual changes.

Either way this is likely something not too complicated to add a check to on the web side unless it would be better handled on the RA_Integration side

**Comment by luchaos** [comment]
Closing, assuming that this is issue has been resolved by now. Please open a new issue if this issue still persists.
