### ISSUE TITLE
Tooltip card position skips for 1 frame

### ISSUE THREAD

**Issue by wescopeland** [RetroAchievements/RAWeb#2155]
**Describe the bug**
When landing on a tooltipped element and immediately stopping the cursor, then resuming motion, you will observe that the tooltip "jumps" to the correct position. This can sometimes result in a disorienting experience.

**To Reproduce**
1. Go to a user profile.
2. Move your cursor to an achievement badge and immediately stop movement.
3. Resume movement.

**Expected behavior**
Tooltip motion should be fluid and seamless, always following the current cursor position.

https://github.com/RetroAchievements/RAWeb/assets/3984985/3e31b981-4ddf-4bed-97f4-f93fba925a4f

**Comment by drisc** [comment]
Which browser are you using? I can't seem to replicate this on Firefox or Safari.

**Comment by wescopeland** [comment]
It's reproducible on every browser. I'm sure this is a logic error somewhere in our Floating UI integration. Here's Firefox:


https://github.com/RetroAchievements/RAWeb/assets/3984985/89cc81ff-cb96-44c8-98c1-458d5ed96674

**Comment by drisc** [comment]
Ah I got it now, I wasn't mousing over the icons fast enough.

**Comment by christianlegge** [comment]
Looks like this happens because the mouseover listener isn't listening until the tooltip component already exists - I'm able to reproduce this consistently by flicking my mouse in from the side of a link and making sure it stops quickly. I'm not sure if there's a way to control the mouseover events finely enough to make sure the "create tooltip" event fires before the "position tooltip" one does - it should already be working that way so I'm thinking this is due to event queue weirdness - but I'm able to fix this behavior by adding an event listener to the document so that the tooltip position is constantly updating, even when one doesn't exist. Not sure if there's a non-negligible performance hit from doing that (certainly nothing I can perceive without profiling), but I figured I'd bring it up here before making a PR.

**Comment by wescopeland** [comment]
> I'm thinking this is due to event queue weirdness - but I'm able to fix this behavior by adding an event listener to the document so that the tooltip position is constantly updating

I vaguely recall when I was poking around with this, I was able to get the issue to stop occurring when I tweaked some the animations and/or timeout logic. Agreed that a document-wide event listener seems like a broad stroke - would prefer a more surgical fix if it's something we can get away with.

**Comment by christianlegge** [comment]
Apologies for muddying the waters with what I said above - looking at this again with fresh eyes the problem seems kind of obvious. The components get created through a setTimeout with 70ms delay, and that callback captures the mouse event coordinates from when it was fired. Changing things around so that they don't get initialized with an absolute position seems to fix the problem entirely. I'll try to get a PR in for this sometime today.
