### ISSUE TITLE
RetroPoints doesn't seem to add up

### ISSUE THREAD

**Issue by zeroquinc** [RetroAchievements/RAWeb#2322]
I have a Discord Bot that sends me a daily notification at 00:00, and checks every 15mins to see if u have any achievements earned, so it sends a notification for that too.

I asked to add TrueRatio field to the GetRecentAchievements API, and that got added so I implemented it into my bot.

I noticed though that the RetroPoints doesn't really add up.
For example at 00:00 I had 91,306 RetroPoints.  (u can see the total points in the footer of the embed)
I also checked this at the website and it was the same value:

![S2hMAVX](https://github.com/RetroAchievements/RAWeb/assets/39315068/170b4891-36f3-4a0c-9660-ab64771911f3)

Since now 9 hours later, I earned 1 achievement, the shiny snorlax from the Gen1 shiny set, which is worth 3511 RetroPoints: 

![6AW0YhD](https://github.com/RetroAchievements/RAWeb/assets/39315068/a14796ff-b149-4822-982f-86b6c19de2b0)

I also double checked this at the website, it's still 3511 RetroPoints.

![8GJsaEP](https://github.com/RetroAchievements/RAWeb/assets/39315068/5626a040-256e-4a16-a691-95cb0fc3a627)

Simple math teaches us that 91,306 + 3511 = 94,817.

Then how come my RetroPoints count is now 93,103?

![zF5S2WC](https://github.com/RetroAchievements/RAWeb/assets/39315068/a183fea5-f533-423e-907b-209face9e9be)

Is this a bug? How come it doesnt just add up?

I have more examples, so this isnt a one time off thing. Anyone maybe knows?

**Comment by zeroquinc** [comment]
Another example: I got a Shiny Voltorb now which has 25 points and 4,678 RetroPoints.

You would expect I have 97,781 RetroPoints now because I had 93,103 before. But I currently have 98,104. 
So where are the extra 323 RetroPoints coming from? There aren't any other achievements earned in the meantime.

**Comment by zeroquinc** [comment]
Another very odd one. You can see yesterday at 00:00 my friend Lipperdie had 132.959 RetroPoints. Then 24hours later he unlocked 1 achievement (which nobody else unlocked in the meantime) and got 4709 RetroPoints for that.

![image](https://github.com/RetroAchievements/RAWeb/assets/39315068/7d61da9c-611e-4fed-935a-8ef5cce70a7b)


Then how is his total amount now 135.123?!

**Comment by wescopeland** [comment]
Hi @zeroquinc ,

Based on a cursory look at the codebase, I am led to believe this is likely functioning as expected.

I believe what's happening is your RetroPoints value is fluctuating because these are totally dynamic values assigned to every achievement on the site.

As you accumulate more unlocks, your account's RetroPoints value becomes more and more volatile at a micro level.

Any time a user unlocks an achievement in hardcore mode, that achievement's RetroPoints value is updated to reflect its new hypothetical rarity.

Any time you unlock an achievement in hardcore mode, a job is dispatched which checks _all_ of the achievements you've unlocked and tallies what your account's new RetroPoints value should be. I believe this explains the discrepancies you may be seeing.

Let me know if this doesn't make sense.

**Comment by zeroquinc** [comment]
@wescopeland Makes complete sense! Thank you explaining! I guess you can close this issue then.
