### ISSUE TITLE
Players able to organize the layout of their mastery badges

### ISSUE THREAD

**Issue by Prism7** [RetroAchievements/RAWeb#252]
I was thinking that it would be a neat feature on the website to have some way for players to organize the game icon trophies on their user pages. Currently, they are displayed in the order they were awarded, but I imagine many of us would prefer to group together games by console, genre, franchise, etc. (e.g. placing Pokemon Red and Blue together even if you mastered them months/years apart).

**Comment by MrOwnership** [comment]
I started working on implementing this on my local instance of the site. This is what I have so far.

I added a new button to the users settings page to reorder site awards
![](https://i.imgur.com/SHeAR7n.png)

Clicking the new button will take you to the new "Reorder Site Awards" page which has the same look as the page to reorder achievements. From here the user can set the order that they want site awards to display in. The right side of the screen shows how the awards will be displayed on the users page so they can have a look at how the 5 awards per row looks.
![](https://i.imgur.com/x853RyB.png)

I don't have updating the database as the user changes the order implemented just yet, but if I manually update the database and refresh the page the site awards are displayed in the new order.
![](https://i.imgur.com/ByOChV9.png)

**Comment by meleu** [comment]
yay! really cool @ MrOwnership !!

**Comment by Krylan** [comment]
It's good. I would also add information about date of getting the award into the tooltip in the profile, if someone would like to check it (for now it shows only "MASTERED + game title").

Also, for better User Experience it would be much more comfortable to simply drag-and-drop awards, than giving them numbers, but then it would be more work for Javascript, than PHP.
Anyway, good job!

**Comment by meleu** [comment]
uh... @MrOwnership I guess it will need a new field in the SiteAwards table, right?

**Comment by MrOwnership** [comment]
@Krylan I agree that a drag-and-drop would be better, the format of this page matches the format of the achievement reordering page. So I just stuck with using same general layout as that page.

@meleu Yeah, I had added in a DisplayOrder field to the siteawards table. Is there going to be a problem with that? The new field has the same attributes that the other DisplayOrder fields have for some of the other tables. I can provide the SQL query to create the field, if we don't already have one, when I make a pull request.

**Comment by kdecks** [comment]
This is a very commonly requested feature! ❤️ 
+1 to drag-and-drop, but whatever solution you find will be a major improvement.

**Comment by luchaos** [comment]
@MrOwnership we're trying to not change the table structure as we do not have proper means yet to roll out database migrations to all developers easily. in v2 this will be a very easy thing to do because of laravel's built in migrations handling.
I don't want to hold anyone back anymore with such changes though, seeing as v1 development picked up quite some momentum, which is great.
so i suggest you add the relevant change to `database/RA_Template_20180212_170235.sql` as well in a given pull-request - or in an additional file which only includes the relevant change (`ALTER` statement).
as long as we keep changes to the data structure clean and comprehensive i'd say we go for it - we'll see how that turns out for all of us.

**Comment by luchaos** [comment]
Deployed to production.
