### ISSUE TITLE
"Merge Game" returns 404 error

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAWeb#253]
Found when trying to merge 7397 into 706.

**Comment by meleu** [comment]
The Merge Game functionality was disabled due to being extremely buggy, vulnerable and not frequently used.

In fact someone abused this vulnerability a few months ago, deleting all game entries. We removed this funcionality (as it wasn't really commonly used) and the links present on some pages are actually just leftovers.

**Comment by rzumer** [comment]
That seems reasonable, but how about displaying a simple message or removing the merge link altogether?

**Comment by meleu** [comment]
sure, I think I'll have some freetime tonight. I'll try to remove those links.

**Comment by rzumer** [comment]
Closed by https://github.com/RetroAchievements/RAWeb/commit/2e0d929f743a7f908a65c52069bf8af08aad072f.
