### ISSUE TITLE
add PC-8800 as a supported system

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#254]
just some notes for self (most likely will be done tonight):
- [x] add a RAQUASI88 entry to `src/Emulators.php`
- [x] add a RAQUASI88 entry to `latestclient` in `public/dorequest.php`

After binary is available (waiting for @rzumer / @Jamiras)
- [x] add the PC-8800 console ID as valid in `isValidConsoleID()` (`lib/database/game.php`)
- [x] create a `LatestRAQUASI88Version.html`
- [x] upload the binary
- [x] add an entry in the downloads page

**Comment by rzumer** [comment]
Also please consider whether the PC-8001 series should have their own category, because the PC-8801 is backwards compatible and I am not aware of any way to differentiate between systems when loading an image (file extensions are the same).

It seems best to rename "PC-8800" to "PC-8000/8800 series" or something similar.
