### ISSUE TITLE
Inconsistent `UserWallActive`'s field types in different endpoint

### ISSUE THREAD

**Issue by TapiocaFox** [RetroAchievements/RAWeb#2616]
**Describe the bug**
`UserWallActive`'s type is inconsistent between different endpoints.

Take a look at response examples from API docs:
### User Profile (Boolean)
```
  "ID": 16446,
  "UserWallActive": true,
  "Motto": "Join me on Twitch! GameSquadSquad for live RA"
```

### User Summary (Integer)
```
  "ID": 224958,
  "UserWallActive": 1,
  "Motto": "",
```

**Expected behavior**
`UserWallActive` is either `Boolean` or `Integer` in every endpoints.

https://github.com/RetroAchievements/api-kotlin/issues/10

**Comment by wescopeland** [comment]
Hi @TapiocaFox! It is good to hear from you. We are big fans of Daijishō.

I agree that it would be desirable for the user summary endpoint to return a boolean for `UserWallActive` instead of an integer. Unfortunately, we have an extremely strict "no breaking changes" policy, and have found that even well-meaning and reasonable changes like this tend to break downstream consumers in bizarre and unexpected ways.

At some point, we intend to build a V2 of the web API that has more best-practices baked in and is a bit more RESTful. Unfortunately, at the current time, I don't believe we'll be able to make this adjustment.

**Comment by TapiocaFox** [comment]
@wescopeland Good point. Thanks for the explanation and your love of Dai. :3
