### ISSUE TITLE
(Suggestion) Add ability to order games by date the achievement list was added (or updated)

### ISSUE THREAD

**Issue by ReptarOnIce3000** [RetroAchievements/RAWeb#507]
So I think it would be great to be able to go to the games list on say, the NES, and see a "Date Add" column, that you can then sort by latest or oldest.

The reason I personally would love this feature is I try to keep an update library of games with achievements, in folders, so that I nicely and neatly only have games with achievements in my RetroArch Library. It can get sort of tedious to keep up with that when adding new games, whenever new games might get added to the list. So far the only real ways to see latest games is by either viewing the sites "Latest Achievements" section, or the "Achievement News" Channel in the Discord. A way to simply filter the games, on each consoles page, would be wonderful!

Another application of this that would be useful to more users and not just my specific circumstance would be maybe you haven't looked at the list in a while, and it would be easier to just filter to "latest added" to see the new things, than trying to comb the list and remember if a game was there before or not.

**Comment by televandalist** [comment]
More sorting/filtering options are always a plus.

The closest we have for that on site is this page: https://retroachievements.org/achievementList.php?s=17&p=3 - but it shows all the achievements rather than just the games that got core achievements. This is more related to #428 though... 

Also, this spreadsheet: https://docs.google.com/spreadsheets/d/1c9YxGYgKz3bzOD0NTKTrxyOD3__IMRXvrZsZkjVReFs/edit?usp=sharing - the "Core" tab has all recent sets and revisions.

**Comment by ReptarOnIce3000** [comment]
That definitely helps a fair bit!
