### ISSUE TITLE
Allow seeing other users' requested sets without logging in

### ISSUE THREAD

**Issue by Alfex3** [RetroAchievements/RAWeb#560]
Sometimes I'm curious about the sets a user has requested and it takes me to the homepage. And if I log in on my mobile phone, it logs me out on my computer.

**Comment by Tsearo** [comment]
From I can tell with a quick test all that needs to be done is to change:
https://github.com/RetroAchievements/RAWeb/blob/111a426503f62e8dc5f78ccbe1b182cd7432906d/public/setRequestList.php#L4-L7 to
`RA_ReadCookieCredentials($user, $points, $truePoints, $unreadMessageCount, $permissions)`

It looks like @luchaos changed this specifically from the above line to what is there now as a performance tweak so it seems intentional.

**Comment by meleu** [comment]
#561 is the preferred solution.

Closing this one.

**Comment by Alfex3** [comment]
Not being able to log in in several devices is something that needs solving. Still, what's wrong with unregistered users being able to see others' requested sets?
