### ISSUE TITLE
[Suggestion] Add 2FA (Two-factor authentication) to Accounts

### ISSUE THREAD

**Issue by Soulsderfuchs** [RetroAchievements/RAWeb#606]
Currently the site uses basic logging functionality ,making breaching of an account easily done if a third party gets hold of the password to said account and in a worst case scenario being capable of requesting deletion of the account or reseting progress on sets.

Adding optional security options such as 2FA would make these accounts more secure for the users.

**Comment by televandalist** [comment]
Here's hoping...

**Comment by Sanaki** [comment]
I'm good with it. It -might- be doable in V1, but someone more familiar with the codebase would have to weigh in. My only fundamental concern is that it needs to be via TOTP (google authenticator and authy being the most common providers), because email-based is the only other viable option, and that's both less secure and less reliable, with some of our users having email issues already on V1.

Topics I see that'd need to be addressed:
* Just implementing it. Straightforward.
* Emulator support. For this one, a few options I see, most with issues...
  * Add a TOTP field for login (not great, since RetroArch login is asynchronous with entry)
  * Allow appending TOTP to the password (not great, see above)
  * Allow a timed disabling of TOTP from the website to fetch a token (over-involved for users, counter to TOTP security)
  * Just ignore TOTP from game clients (most viable, least secure)
  * Allow generating a one-use client password after site login which can be used to log in a single game client (probably the best option available, but may push it out of V1 viability)
  * Update RetroArch login to attempt login through settings, rather than on hash validation. Add a TOTP field in the process.
* Password/account recovery policy becomes something we need to seriously contemplate, since users will inevitably lock themselves out (primarily through user error).
